global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 0.5
  resolution: 0.05
  static_map: true
  rolling_window: false
  robot_radius: 0.3
  plugins: 
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    #- {name: proxemic, type: "social_navigation_layers::ProxemicLayer"}
    #- {name: passing, type: "social_navigation_layers::PassingLayer"}
    
  inflation_layer:
    enabled:              true
    cost_scaling_factor:  10.0  #10.0 exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.5  #0.5 max. distance from an obstacle at which costs are incurred for planning paths.

  static_layer:
    enabled:              true
    map_topic:            "map"
    
  obstacles_layer:
    observation_sources: base_scan
    base_scan: {data_type: LaserScan, sensor_frame: laser, clearing: true, marking: true, topic: /scan,}

  #proxemic:
  #  enabled: True #Whether to apply this plugin or not
  #  cutoff: 10.0 #Smallest value to publish on costmap adjustments
  #  amplitude: 90.0 #Amplitude of adjustments at peak
  #  covariance: 0.25 #Covariance of adjustments
  #  factor: 5.0 #Factor with which to scale the velocity
  #  keep_time: 0.75 #Pause before clearing leg list

  #passing:
  #  enabled: True #Whether to apply this plugin or not
  #  cutoff: 10.0 #Smallest value to publish on costmap adjustments
  #  amplitude: 90.0 #Amplitude of adjustments at peak
  #  covariance: 0.25 #Covariance of adjustments
  #  factor: 5.0 #Factor with which to scale the velocity
  #  keep_time: 0.75 #Pause before clearing leg list